# -*- coding: utf-8 -*-
"""Uganda Economic Pulse_Capstone Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gHbB_LGwIx8Xgu5lJOOfZRashU60B6Te

**Economic Monitoring, Risk Analysis & Growth Outlook**

Uganda Economic Pulse is a data-driven economic intelligence dashboard designed to monitor Uganda’s economic performance, identify emerging risks and assess the near-term growth outlook. Using automated public data ingestion, SQL analytics, interactive visualizations, risk scoring and GDP forecasting.

The dashboard transforms key economic indicators into actionable insights for understanding Uganda’s changing economic landscape.

**Data source:** World Bank Indicators API
https://api.worldbank.org/v2/country/UG/indicator/{CODE}?format=json
"""

"""Imported libraries and defined project settings"""

!pip -q install duckdb statsmodels streamlit plotly

import requests, duckdb, numpy as np, pandas as pd
import plotly.graph_objects as go
from statsmodels.tsa.arima.model import ARIMA
from datetime import datetime, timezone

DB = "/content/uganda_economic.duckdb"
BASE = "https://api.worldbank.org/v2/country/UGA/indicator"

INDICATORS = {
    "GDP Growth":"NY.GDP.MKTP.KD.ZG",
    "Inflation":"FP.CPI.TOTL.ZG",
    "Unemployment":"SL.UEM.TOTL.ZS",
    "Exports":"NE.EXP.GNFS.ZS",
    "Imports":"NE.IMP.GNFS.ZS",
    "Poverty":"SI.POV.DDAY"
}

"""Fetch Uganda's data"""

def fetch(code, name):
    r = requests.get(
        f"{BASE}/{code}",
        params={"format":"json", "per_page":1000}
    ).json()[1]

    return [{
        "country":"Uganda",
        "indicator":name,
        "code":code,
        "year":int(x["date"]),
        "value":float(x["value"]),
        "fetched_at":datetime.now(timezone.utc)
    } for x in r if x["value"] is not None]

data = pd.DataFrame(
    sum([fetch(code,name) for name,code in INDICATORS.items()], [])
).sort_values(["indicator","year"])

display(data.tail(10))

"""Store in DuckDB and create trade balance"""

con = duckdb.connect(DB)

con.execute("DROP TABLE IF EXISTS economic_indicators")

con.register("df", data)

con.execute("""
CREATE TABLE economic_indicators AS
SELECT * FROM df
""")

trade = con.execute("""
SELECT year,
       MAX(CASE WHEN indicator='Exports' THEN value END) exports,
       MAX(CASE WHEN indicator='Imports' THEN value END) imports
FROM economic_indicators
GROUP BY year
ORDER BY year
""").df()

trade["trade_balance"] = trade.exports - trade.imports

display(trade.tail())

"""Risk engine"""

def risk(value, thresholds):
    return np.digitize(value, thresholds)

latest = (
    data.sort_values("year")
        .groupby("indicator")
        .tail(1)
)

v = latest.set_index("indicator")["value"]

# Risk scores: 0 = Low, 1 = Moderate, 2 = High
scores = {
    "GDP Growth": risk(v["GDP Growth"], [3, 5]),
    "Inflation": risk(v["Inflation"], [5, 8]),
    "Unemployment": risk(v["Unemployment"], [5, 8]),
    "Poverty": risk(v["Poverty"], [20, 40])
}

# Trade deficit risk
trade_balance = trade.iloc[-1]["trade_balance"]
scores["Trade"] = risk(-trade_balance, [0, 5])

levels = {
    0: "Low",
    1: "Moderate",
    2: "High"
}

risk_table = pd.DataFrame({
    "Indicator": list(scores.keys()),
    "Risk": [levels[x] for x in scores.values()]
})

# Convert the 0–2 scores to a 0–100 overall score
overall = round(
    np.mean(list(scores.values())) * 50,
    1
)

overall_level = (
    "Low" if overall <= 39
    else "Moderate" if overall <= 69
    else "High"
)

display(risk_table)

print(f"Overall Risk: {overall_level} ({overall}/100)")

"""GDP Forecast"""

gdp = (
    data[data.indicator=="GDP Growth"]
    .sort_values("year")
    .set_index("year")["value"]
)

model = ARIMA(gdp, order=(1,1,1)).fit()
forecast = model.get_forecast(3)

fc = pd.DataFrame({
    "year":range(gdp.index.max()+1,gdp.index.max()+4),
    "forecast":forecast.predicted_mean.values,
    "lower":forecast.conf_int().iloc[:,0].values,
    "upper":forecast.conf_int().iloc[:,1].values
})

display(fc)

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=gdp.index, y=gdp.values,
    mode="lines+markers",
    name="Historical"
))

fig.add_trace(go.Scatter(
    x=list(fc.year)+list(fc.year[::-1]),
    y=list(fc.upper)+list(fc.lower[::-1]),
    fill="toself",
    name="95% Interval"
))

fig.add_trace(go.Scatter(
    x=fc.year, y=fc.forecast,
    mode="lines+markers",
    name="Forecast",
    line=dict(dash="dash")
))

fig.update_layout(
    title="Uganda GDP Growth Forecast",
    xaxis_title="Year",
    yaxis_title="GDP Growth (%)",
    template="plotly_white"
)

fig.show()

"""Streamlit dashboard"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import duckdb, pandas as pd
# import plotly.express as px
# 
# st.set_page_config(
#     page_title="Uganda Economic Pulse",
#     page_icon="🇺🇬",
#     layout="wide"
# )
# 
# st.title("🇺🇬 Uganda Economic Pulse")
# st.caption("Economic Monitoring, Risk Detection & GDP Forecasting")
# 
# con = duckdb.connect(
#     "/content/uganda_economic.duckdb",
#     read_only=True
# )
# 
# df = con.execute("""
# SELECT * FROM economic_indicators
# ORDER BY year
# """).df()
# 
# # Sidebar
# indicator = st.sidebar.selectbox(
#     "Indicator",
#     df.indicator.unique()
# )
# 
# # Latest values
# latest = (
#     df.sort_values("year")
#       .groupby("indicator")
#       .tail(1)
#       .set_index("indicator")
# )
# 
# c1,c2,c3,c4 = st.columns(4)
# 
# c1.metric("GDP Growth",
#           f"{latest.loc['GDP Growth','value']:.1f}%")
# 
# c2.metric("Inflation",
#           f"{latest.loc['Inflation','value']:.1f}%")
# 
# c3.metric("Unemployment",
#           f"{latest.loc['Unemployment','value']:.1f}%")
# 
# exports = latest.loc["Exports","value"]
# imports = latest.loc["Imports","value"]
# 
# c4.metric(
#     "Trade Balance",
#     f"{exports-imports:.1f}% GDP"
# )
# 
# st.divider()
# 
# # Indicator chart
# x = df[df.indicator == indicator]
# 
# fig = px.line(
#     x, x="year", y="value",
#     markers=True,
#     title=f"{indicator} — Uganda"
# )
# 
# st.plotly_chart(
#     fig,
#     use_container_width=True
# )
# 
# st.subheader("Economic Risk")
# 
# st.info(
#     f"Overall Risk: **{overall_level}** "
#     f"({overall}/100)"
# )
# 
# st.caption(
#     "Risk score is an analytical framework developed "
#     "for this dashboard, not an official classification."
# )
# 
# st.subheader("Risk by Indicator")
# 
# st.dataframe(
#     risk_table,
#     use_container_width=True,
#     hide_index=True
# )
